# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\dow_troop_counters.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1347, 872)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(280, 30, 151, 16))
        self.label_2.setObjectName("label_2")
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(513, 20, 31, 831))
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(30, 30, 151, 16))
        self.label.setObjectName("label")
        self.opponentRaceList = QtWidgets.QListWidget(self.centralwidget)
        self.opponentRaceList.setGeometry(QtCore.QRect(30, 60, 211, 591))
        self.opponentRaceList.setObjectName("opponentRaceList")
        self.opponentUnitList = QtWidgets.QListWidget(self.centralwidget)
        self.opponentUnitList.setGeometry(QtCore.QRect(280, 60, 211, 591))
        self.opponentUnitList.setObjectName("opponentUnitList")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(30, 670, 31, 16))
        self.label_3.setObjectName("label_3")
        self.opponentUnitNameLabel = QtWidgets.QLabel(self.centralwidget)
        self.opponentUnitNameLabel.setGeometry(QtCore.QRect(50, 690, 191, 16))
        self.opponentUnitNameLabel.setText("")
        self.opponentUnitNameLabel.setObjectName("opponentUnitNameLabel")
        self.opponentFileNameLabel = QtWidgets.QLabel(self.centralwidget)
        self.opponentFileNameLabel.setGeometry(QtCore.QRect(50, 740, 191, 16))
        self.opponentFileNameLabel.setText("")
        self.opponentFileNameLabel.setObjectName("opponentFileNameLabel")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(30, 720, 101, 16))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(30, 780, 101, 16))
        self.label_5.setObjectName("label_5")
        self.opponentArmourTypeLabel = QtWidgets.QLabel(self.centralwidget)
        self.opponentArmourTypeLabel.setGeometry(QtCore.QRect(50, 800, 201, 16))
        self.opponentArmourTypeLabel.setText("")
        self.opponentArmourTypeLabel.setObjectName("opponentArmourTypeLabel")
        self.opponentUnitWeaponList = QtWidgets.QListWidget(self.centralwidget)
        self.opponentUnitWeaponList.setGeometry(QtCore.QRect(280, 690, 211, 121))
        self.opponentUnitWeaponList.setObjectName("opponentUnitWeaponList")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(280, 670, 141, 16))
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(550, 30, 191, 16))
        self.label_7.setObjectName("label_7")
        self.playerRaceList = QtWidgets.QListWidget(self.centralwidget)
        self.playerRaceList.setGeometry(QtCore.QRect(550, 60, 211, 591))
        self.playerRaceList.setObjectName("playerRaceList")
        self.playerCounterTable = QtWidgets.QTableWidget(self.centralwidget)
        self.playerCounterTable.setGeometry(QtCore.QRect(790, 60, 531, 591))
        self.playerCounterTable.setObjectName("playerCounterTable")
        self.playerCounterTable.setColumnCount(0)
        self.playerCounterTable.setRowCount(0)
        self.statusLabelTitle = QtWidgets.QLabel(self.centralwidget)
        self.statusLabelTitle.setGeometry(QtCore.QRect(560, 780, 41, 41))
        self.statusLabelTitle.setObjectName("statusLabelTitle")
        self.statusLabel = QtWidgets.QLabel(self.centralwidget)
        self.statusLabel.setGeometry(QtCore.QRect(610, 780, 451, 41))
        self.statusLabel.setText("")
        self.statusLabel.setObjectName("statusLabel")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1347, 21))
        self.menubar.setObjectName("menubar")
        self.menuWhat = QtWidgets.QMenu(self.menubar)
        self.menuWhat.setObjectName("menuWhat")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionDewit = QtWidgets.QAction(MainWindow)
        self.actionDewit.setObjectName("actionDewit")
        self.menuWhat.addAction(self.actionDewit)
        self.menubar.addAction(self.menuWhat.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_2.setText(_translate("MainWindow", "Unit you\'re trying to counter"))
        self.label.setText(_translate("MainWindow", "Race you\'re trying to counter"))
        self.label_3.setText(_translate("MainWindow", "Unit:"))
        self.label_4.setText(_translate("MainWindow", "Filename:"))
        self.label_5.setText(_translate("MainWindow", "Armour Type:"))
        self.label_6.setText(_translate("MainWindow", "Unit Weapons:"))
        self.label_7.setText(_translate("MainWindow", "Choose race for find counter from"))
        self.statusLabelTitle.setText(_translate("MainWindow", "Status:"))
        self.menuWhat.setTitle(_translate("MainWindow", "Generate Data"))
        self.actionDewit.setText(_translate("MainWindow", "Dewit"))
