# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\dow_troop_counters_updated.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1112, 817)
        MainWindow.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.opponentUnitList = QtWidgets.QListWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.opponentUnitList.sizePolicy().hasHeightForWidth())
        self.opponentUnitList.setSizePolicy(sizePolicy)
        self.opponentUnitList.setMinimumSize(QtCore.QSize(200, 500))
        self.opponentUnitList.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.opponentUnitList.setProperty("showDropIndicator", False)
        self.opponentUnitList.setDefaultDropAction(QtCore.Qt.IgnoreAction)
        self.opponentUnitList.setObjectName("opponentUnitList")
        self.gridLayout.addWidget(self.opponentUnitList, 2, 3, 1, 1)
        self.playerCounterTable = QtWidgets.QTableWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.playerCounterTable.sizePolicy().hasHeightForWidth())
        self.playerCounterTable.setSizePolicy(sizePolicy)
        self.playerCounterTable.setMinimumSize(QtCore.QSize(420, 0))
        self.playerCounterTable.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.playerCounterTable.setProperty("showDropIndicator", False)
        self.playerCounterTable.setDragDropOverwriteMode(False)
        self.playerCounterTable.setAlternatingRowColors(True)
        self.playerCounterTable.setObjectName("playerCounterTable")
        self.playerCounterTable.setColumnCount(0)
        self.playerCounterTable.setRowCount(0)
        self.playerCounterTable.horizontalHeader().setVisible(True)
        self.playerCounterTable.horizontalHeader().setCascadingSectionResizes(True)
        self.playerCounterTable.horizontalHeader().setDefaultSectionSize(132)
        self.playerCounterTable.horizontalHeader().setMinimumSectionSize(40)
        self.playerCounterTable.horizontalHeader().setSortIndicatorShown(True)
        self.playerCounterTable.horizontalHeader().setStretchLastSection(True)
        self.playerCounterTable.verticalHeader().setVisible(False)
        self.gridLayout.addWidget(self.playerCounterTable, 2, 7, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(5, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 2, 1, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(5, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem1, 2, 6, 1, 1)
        self.label = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 0, 3, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(False)
        font.setUnderline(False)
        font.setWeight(50)
        self.label_3.setFont(font)
        self.label_3.setAutoFillBackground(False)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 0, 5, 1, 1)
        self.playerRaceList = QtWidgets.QListWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.playerRaceList.sizePolicy().hasHeightForWidth())
        self.playerRaceList.setSizePolicy(sizePolicy)
        self.playerRaceList.setMinimumSize(QtCore.QSize(200, 500))
        self.playerRaceList.setSizeIncrement(QtCore.QSize(0, 50))
        self.playerRaceList.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.playerRaceList.setProperty("showDropIndicator", False)
        self.playerRaceList.setDefaultDropAction(QtCore.Qt.IgnoreAction)
        self.playerRaceList.setObjectName("playerRaceList")
        self.gridLayout.addWidget(self.playerRaceList, 2, 5, 1, 1)
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setMinimumSize(QtCore.QSize(20, 0))
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.gridLayout.addWidget(self.line, 2, 4, 1, 1)
        self.opponentRaceList = QtWidgets.QListWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.opponentRaceList.sizePolicy().hasHeightForWidth())
        self.opponentRaceList.setSizePolicy(sizePolicy)
        self.opponentRaceList.setMinimumSize(QtCore.QSize(200, 500))
        self.opponentRaceList.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.opponentRaceList.setProperty("showDropIndicator", False)
        self.opponentRaceList.setDefaultDropAction(QtCore.Qt.IgnoreAction)
        self.opponentRaceList.setObjectName("opponentRaceList")
        self.gridLayout.addWidget(self.opponentRaceList, 2, 0, 1, 1)
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setMinimumSize(QtCore.QSize(200, 200))
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.label_4 = QtWidgets.QLabel(self.groupBox)
        self.label_4.setGeometry(QtCore.QRect(10, 30, 31, 16))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.groupBox)
        self.label_5.setGeometry(QtCore.QRect(10, 140, 101, 16))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.opponentFileNameLabel = QtWidgets.QLabel(self.groupBox)
        self.opponentFileNameLabel.setGeometry(QtCore.QRect(30, 100, 191, 16))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.opponentFileNameLabel.setFont(font)
        self.opponentFileNameLabel.setText("")
        self.opponentFileNameLabel.setObjectName("opponentFileNameLabel")
        self.opponentArmourTypeLabel = QtWidgets.QLabel(self.groupBox)
        self.opponentArmourTypeLabel.setGeometry(QtCore.QRect(30, 160, 201, 16))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.opponentArmourTypeLabel.setFont(font)
        self.opponentArmourTypeLabel.setText("")
        self.opponentArmourTypeLabel.setObjectName("opponentArmourTypeLabel")
        self.opponentUnitNameLabel = QtWidgets.QLabel(self.groupBox)
        self.opponentUnitNameLabel.setGeometry(QtCore.QRect(30, 50, 191, 16))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.opponentUnitNameLabel.setFont(font)
        self.opponentUnitNameLabel.setText("")
        self.opponentUnitNameLabel.setObjectName("opponentUnitNameLabel")
        self.label_6 = QtWidgets.QLabel(self.groupBox)
        self.label_6.setGeometry(QtCore.QRect(10, 80, 101, 16))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.groupBox, 3, 0, 1, 4)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.gridLayout.addLayout(self.gridLayout_2, 1, 0, 1, 1)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.verticalLayout_4.addWidget(self.label_7)
        self.opponentUnitWeaponList = QtWidgets.QListWidget(self.centralwidget)
        self.opponentUnitWeaponList.setEnabled(True)
        self.opponentUnitWeaponList.setMinimumSize(QtCore.QSize(200, 200))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.opponentUnitWeaponList.setFont(font)
        self.opponentUnitWeaponList.setToolTip("")
        self.opponentUnitWeaponList.setToolTipDuration(1)
        self.opponentUnitWeaponList.setStatusTip("")
        self.opponentUnitWeaponList.setWhatsThis("")
        self.opponentUnitWeaponList.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.opponentUnitWeaponList.setProperty("showDropIndicator", False)
        self.opponentUnitWeaponList.setSelectionMode(QtWidgets.QAbstractItemView.NoSelection)
        self.opponentUnitWeaponList.setLayoutMode(QtWidgets.QListView.SinglePass)
        self.opponentUnitWeaponList.setBatchSize(102)
        self.opponentUnitWeaponList.setObjectName("opponentUnitWeaponList")
        self.verticalLayout_4.addWidget(self.opponentUnitWeaponList)
        self.gridLayout.addLayout(self.verticalLayout_4, 3, 4, 1, 4)
        self.verticalLayout.addLayout(self.gridLayout)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1112, 21))
        self.menubar.setObjectName("menubar")
        self.menuGenerate_Data = QtWidgets.QMenu(self.menubar)
        self.menuGenerate_Data.setObjectName("menuGenerate_Data")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionDewit = QtWidgets.QAction(MainWindow)
        self.actionDewit.setObjectName("actionDewit")
        self.menuGenerate_Data.addAction(self.actionDewit)
        self.menubar.addAction(self.menuGenerate_Data.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "DoW Troop Counters"))
        self.playerCounterTable.setSortingEnabled(False)
        self.label.setText(_translate("MainWindow", "Race you are trying to counter"))
        self.label_2.setText(_translate("MainWindow", "Unit you are trying to counter"))
        self.label_3.setText(_translate("MainWindow", "Race you are playing"))
        self.opponentRaceList.setSortingEnabled(False)
        self.label_4.setText(_translate("MainWindow", "Unit:"))
        self.label_5.setText(_translate("MainWindow", "Armour Type:"))
        self.label_6.setText(_translate("MainWindow", "Filename:"))
        self.label_7.setText(_translate("MainWindow", "Unit\'s possible weapons"))
        self.menuGenerate_Data.setTitle(_translate("MainWindow", "Generate Data"))
        self.actionDewit.setText(_translate("MainWindow", "Dewit"))
